# Generated by Django 4.1.2 on 2022-10-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapp', '0004_answer_modify_date_question_modify_date_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
