# Generated by Django 4.1.1 on 2022-10-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_class', models.CharField(max_length=20)),
                ('sub_class', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('road_name', models.CharField(max_length=50)),
                ('latlng', models.CharField(max_length=50)),
                ('etc', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
